// ClientAngular/to-do-client/src/app/components/to-dos/to-dos.component.ts
import { Component, OnInit } from '@angular/core';
import { finalize, first} from 'rxjs';
import { ToDo } from 'src/app/models/to-do-model';
import { AlertService } from 'src/app/services/alert.service';
import { TodoService } from 'src/app/services/todo.service';

@Component({
  selector: 'app-to-dos',
  templateUrl: './to-dos.component.html',
  styleUrls: ['./to-dos.component.css']
})
export class ToDosComponent implements OnInit {
  data: ToDo[] = [];
  fetchLoading = true;
  populateLoading = false;
  isAddViewVisible = false;
  constructor(private toDoService: TodoService, private alertService: AlertService) {}

  ngOnInit(): void {
    this.fetchData();
  }

  handleAddToDoClicked() {
    this.isAddViewVisible = !this.isAddViewVisible;
  }

  onItemModified(success: boolean) {
    if(success) {
      this.alertService.open('success', 'Dane zostały zapisane.');
      this.fetchData();
    } else {
        this.alertService.open('danger', 'Wystąpił błąd!');
      }
  }

  fetchData() {
    this.fetchLoading = true;
    this.toDoService.loadToDos().pipe(
      first(),
      finalize(() => this.fetchLoading = false)
      ).subscribe(response => {
        this.data = response;
    })
  }

  populateData(count: number) {
    this.populateLoading = true;
    this.toDoService.populateData(count).pipe(
      first(),
      finalize(() => this.populateLoading = false)
      ).subscribe(response => {
        this.data = response;
    })
  }
}

<app-header (addClicked)="handleAddToDoClicked()" (itemAdded)="fetchData()"></app-header>
<div *ngIf="fetchLoading" class="d-flex justify-content-center">
    <div class="spinner-border" style="width: 3rem; height: 3rem; margin-top: 3rem;" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
<ng-container *ngIf="!fetchLoading">
    <div class="data" 
    [ngClass]="{ 'large' : !isAddViewVisible, 'medium' : isAddViewVisible }">
        <div *ngIf="!data.length" class="alert alert-warning" role="alert">
            Brak danych!
        </div>
        <app-to-do-item 
        *ngFor="let item of data; let i = index" 
        [toDo]="item"
        [index]="i + 1"
        (itemModified)="onItemModified($event)"
        ></app-to-do-item>
    </div>
</ng-container>
<app-data-generator [loading]="populateLoading" (populateClicked)="populateData($event)"></app-data-generator>

// ClientVue/to-do-client/src/views/ToDos.vue
<template>
    <HeaderComponent @itemAdded="fetchData()" @addClicked="handleAddToDoClicked(value)" />
    <div v-if="fetchLoading" class="d-flex justify-content-center">
        <div class="spinner-border" style="width: 3rem; height: 3rem; margin-top: 3rem;" role="status">
        <span class="visually-hidden">Loading...</span>
        </div>
    </div>
    <div v-if="!fetchLoading" class="data" :class="{'large': !this.isAddViewVisible, 'medium': this.isAddViewVisible}">
        <div v-if="!data.length" class="alert alert-warning" role="alert">
            Brak danych!
        </div>
        <ToDoItem v-for="(item, index) in data" :key="item.id" :toDo="item" :index="index + 1" @item-modified="onItemModified"/>
    </div>
    <DataGenerator @populate-clicked="populateData" :loading="populateLoading" />
</template>

<script>
import HeaderComponent from '../components/Header.vue'
import ToDoItem from '../components/ToDoItem.vue'
import DataGenerator from '../components/DataGenerator.vue';
import TodoService from '@/services/todo-service'
import AlertService from '@/services/alert-service';
const toDoService = new TodoService();
const alertService = new AlertService();
export default {
    name: 'ToDosComponent',
    components: { HeaderComponent, ToDoItem, DataGenerator },
    data() {
        return {
            data: [],
            fetchLoading: true,
            populateLoading: false,
            isAddViewVisible: false
        }
    },
    mounted() {
        this.fetchData();
    },
    methods: {
        handleAddToDoClicked() {
            this.isAddViewVisible = !this.isAddViewVisible;
        },
        onItemModified(success) {
            if(success) {
                alertService.open('success', 'Dane zostały zapisane.');
                this.fetchData();
            } else {
                alertService.open('danger', 'Wystąpił błąd!');
            }
        },
        fetchData() {
            this.fetchLoading = true;
            toDoService.loadToDos().then(response => {
                this.data = response.data;
                this.fetchLoading = false;
            })
        },
        populateData(count) {
            this.populateLoading = true;
            toDoService.populateData(count).then(response => {
                this.data = response.data;
                this.populateLoading = false;
            })
        },
    }
}
</script>

<style>
.data {
    overflow-y: auto;
    overflow-x: hidden;
}

.large {
    min-height: 62vh;
    max-height: 63vh;
}

.medium {
    min-height: 38vh;
    max-height: 39vh;
}
</style>
