// ClientAngular/to-do-client/src/app/components/add-to-do/add-to-do.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { finalize, first } from 'rxjs';
import { ToDo } from 'src/app/models/to-do-model';
import { AlertService } from 'src/app/services/alert.service';
import { TodoService } from 'src/app/services/todo.service';

@Component({
  selector: 'app-add-to-do',
  templateUrl: './add-to-do.component.html',
  styleUrls: ['./add-to-do.component.css']
})
export class AddToDoComponent {
  @Output() itemAdded: EventEmitter<void> = new EventEmitter<void>();
  text: string = '';
  dueDate: string = '';
  loading = false;

  constructor(private toDoService: TodoService, private alertService: AlertService) {}

  onSubmit() {
    if (!this.text || !this.dueDate) {
      this.alertService.open('danger', 'Proszę uzupełnić wszystkie pola!');
    } else {
      this.loading = true;
      const newToDo: ToDo = {
        text: this.text,
        dueDate: this.dueDate
      };
      this.toDoService.createToDo(newToDo).pipe(
        first(), 
        finalize(() => this.loading = false)
        ).subscribe({
        next: () => {
          this.alertService.open('success', 'Dane zostały zapisane.');
          this.itemAdded.emit();
        },
        error: () => {
          this.alertService.open('danger', 'Wystąpił błąd!');
        }
      })
    }
  }
}

<form class="add-form">
      <label for="text">Treść</label>
      <input
        type="text"
        name="text"
        [(ngModel)]="text"
        id="text"
        placeholder="Treść zadania"
        class="form-control"
      />
      <label for="dueDate">Termin wykonania</label>
      <input
        type="text"
        name="dueDate"
        [(ngModel)]="dueDate"
        id="dueDate"
        placeholder="Obsługiwany format: yyyy-mm-dd"
        class="form-control"
      />
    <button (click)="onSubmit()" class="btn btn-dark block">
      <span *ngIf="loading" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
      <span *ngIf="!loading">Zapisz</span>
    </button>
</form>

// ClientVue/to-do-client/src/components/AddToDo.vue
<template>
    <form @submit.prevent="onSubmit" class="add-form">
      <label for="text">Treść</label>
      <input
        type="text"
        name="text"
        id="text"
        placeholder="Treść zadania"
        class="form-control"
        v-model="text"
      />
      <label for="dueDate">Termin wykonania</label>
      <input
        type="text"
        name="dueDate"
        id="dueDate"
        placeholder="Obsługiwany format: yyyy-mm-dd"
        class="form-control"
        v-model="dueDate"
      />
    <button class="btn btn-dark block">
      <span v-if="createLoading" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
      <span v-if="!createLoading">Zapisz</span>
    </button>
  
  </form>
</template>

<script>
import AlertService from '../services/alert-service'
import TodoService from '@/services/todo-service';
const alertService = new AlertService();
const toDoService = new TodoService();
export default {
  name: 'AddToDoComponent',
  data() {
    return {
        text: '',
        dueDate: '',
        createLoading: false
    }
  },
  methods: {
    onSubmit() {
    if (!this.text || !this.dueDate) {
      alertService.open('danger', 'Proszę uzupełnić wszystkie pola!');
    } else {
      const newToDo = {
        text: this.text,
        dueDate: this.dueDate,
        done: false
      };
      this.createToDo(newToDo);
    }
  },
  createToDo(toDo) {
    this.createLoading = true;
    toDoService.createToDo(toDo).then(() => {
      alertService.open('success', 'Dane zostały zapisane.')
      this.createLoading = false;
      this.$emit('itemAdded')
    })
    .catch(() => {
      alertService.open('danger', 'Wystąpił błąd!')
      this.createLoading = false;
    })
  }
  },
  emits: ['itemAdded']
}
</script>

<style>
    .add-form {
        margin-bottom: 20px;
    }

    .block {
        width: 100%;
    }
</style>
