// ClientAngular/to-do-client/src/app/components/data-generator/data-generator.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-data-generator',
  templateUrl: './data-generator.component.html',
  styleUrls: ['./data-generator.component.css']
})
export class DataGeneratorComponent {
  @Input() loading!: boolean
  @Output() populateClicked: EventEmitter<number> = new EventEmitter<number>();
  populateCount: number = 0;

  generateClicked() {
    this.populateClicked.emit(this.populateCount);
  }
}

<div class="flex">
    <button (click)="generateClicked()" class="btn btn-primary">
        <span *ngIf="loading" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
        <span *ngIf="!loading">Wygeneruj dane</span>
    </button>
    <div>
        <label for="populateCount">Ilość rzeczy do zrobienia</label>
        <input
        type="text"
        name="populateCount"
        [(ngModel)]="populateCount"
        id="populateCount"
        class="form-control"
        />
    </div>
</div>

// ClientVue/to-do-client/src/components/DataGenerator.vue
<template>
    <div class="flex">
    <button @click="generateClicked()" class="btn btn-primary">
        <span v-if="loading" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
        <span v-if="!loading">Wygeneruj dane</span>
    </button>
    <div>
        <label for="populateCount">Ilość rzeczy do zrobienia</label>
        <input
        type="text"
        name="populateCount"
        v-model="populateCount"
        id="populateCount"
        class="form-control"
        />
    </div>
</div>
</template>
<script>
export default {
  name: 'DataGenerator',
  data() {
    return {
       populateCount: 0
    }
  },
  props: {
    loading: Boolean
  },
  methods: {
    generateClicked() {
        console.log(this.populateCount);
        this.$emit('populate-clicked', this.populateCount)
    }
  },
  emits: ['populate-clicked']
}
</script>

<style>
    .flex {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
</style>
